import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/app/ui/components/Header';
import { Suspense } from 'react';
import Loader from '@/app/ui/components/Loader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Star Wars App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col h-screen`}>
        <Header></Header>
        <Suspense fallback={<Loader/>}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
